In [ ]:
# Challenge 
# Consider that you have an array like this:
#array([[ 232,   11,   22],
#       [ 333, 4434,   52],
#       [  36,   74,   83]])
#replace the values grater than 100 with 1 and less than 100 with 0

In [1]:
import numpy as np

In [2]:
a  = np.array([[ 232,   11,   22],
       [ 333, 4434,   52],
       [  36,   74,   83]])

In [3]:
b = a > 100 #this will return true for all the greater values
c = a < 100 #this will return true for all the lesser values

print(b)
print(c)

[[ True False False]
 [ True  True False]
 [False False False]]
[[False  True  True]
 [False False  True]
 [ True  True  True]]


In [4]:
a[b] = 1
a[c] = 0
print(a)

[[1 0 0]
 [1 1 0]
 [0 0 0]]
