# Numpy Session

In [1]:
pip install numpy


Note: you may need to restart the kernel to use updated packages.


In [2]:
#importing numpy

import numpy as np

# Creating an array 

In [3]:
#1-D Array

fruits = np.array(['Apple', 'Banana', 'Orange'])
fruits

array(['Apple', 'Banana', 'Orange'], dtype='<U6')

In [4]:
price = np.array([5,5,5])
price

array([5, 5, 5])

In [5]:
type(fruits)

numpy.ndarray

In [6]:
type(price)

numpy.ndarray

In [7]:
len(fruits)

3

In [8]:
len(price)

3

In [9]:
fruits[0:]

array(['Apple', 'Banana', 'Orange'], dtype='<U6')

In [10]:
price.mean()

5.0

In [11]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [12]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [13]:
np.empty(5)

array([1., 1., 1., 1., 1.])

In [14]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
np.arange(2,20)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [16]:
np.arange(2,20,1.2)

array([ 2. ,  3.2,  4.4,  5.6,  6.8,  8. ,  9.2, 10.4, 11.6, 12.8, 14. ,
       15.2, 16.4, 17.6, 18.8])

In [17]:
#line space

np.linspace(1,10, num= 5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [18]:
np.ones(3, dtype=np.int8)

array([1, 1, 1], dtype=int8)

In [19]:
np.ones(3, dtype=np.float64)

array([1., 1., 1.])

# Array Functions

In [20]:
a = np.array([22,56,32,65,1,84,3,21,56,1,0])
a

array([22, 56, 32, 65,  1, 84,  3, 21, 56,  1,  0])

In [21]:
a.sort()

In [22]:
a


array([ 0,  1,  1,  3, 21, 22, 32, 56, 56, 65, 84])

In [23]:
b = np.array([22.0,66.3,11.2,44.5,77,1,0.0,4])
b

array([22. , 66.3, 11.2, 44.5, 77. ,  1. ,  0. ,  4. ])

In [24]:
c = np.concatenate((a,b))
c

array([ 0. ,  1. ,  1. ,  3. , 21. , 22. , 32. , 56. , 56. , 65. , 84. ,
       22. , 66.3, 11.2, 44.5, 77. ,  1. ,  0. ,  4. ])

In [25]:
c.sort()

In [26]:
c

array([ 0. ,  0. ,  1. ,  1. ,  1. ,  3. ,  4. , 11.2, 21. , 22. , 22. ,
       32. , 44.5, 56. , 56. , 65. , 66.3, 77. , 84. ])

In [48]:
#3-D array

a = np.array([
    [[1,2,3],
     [3,4,3]],
    
    [[5,6,3],
     [7,8,3]],
    
    [[9,10,3],
     [11,12,3]]
])
a

array([[[ 1,  2,  3],
        [ 3,  4,  3]],

       [[ 5,  6,  3],
        [ 7,  8,  3]],

       [[ 9, 10,  3],
        [11, 12,  3]]])

In [45]:
a.size

18

In [46]:
a.shape

(3, 2, 3)

In [39]:
#how to find the dimentions 
a.ndim

3

In [41]:
a = np.array([[1,2,3],
             [4,5,6],
             [7,8,9]])
a


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [42]:
a.ndim


2

In [43]:
a.shape

(3, 3)

In [53]:
a= np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [57]:
a.reshape(1,10)

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [59]:
a = np.arange(9)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [60]:
a.shape

(9,)

In [61]:
a.ndim

1

In [62]:
a.size

9

In [63]:
a = a[np.newaxis, : ]
a

array([[0, 1, 2, 3, 4, 5, 6, 7, 8]])

In [64]:
a.ndim

2

In [65]:
a.shape

(1, 9)

In [66]:
a.size

9

In [67]:
a.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [68]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [69]:
a*2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [70]:
a+2

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [71]:
a-2

array([-2, -1,  0,  1,  2,  3,  4,  5,  6,  7])

In [72]:
a/2

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [73]:
a.sum()

45

In [74]:
a.mean()

4.5